version: '3'

services:
  authenticate:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - redis
    networks:
      my-network:
        ipv4_address: 172.16.238.2

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      my-network:
        ipv4_address: 172.16.238.3

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      my-network:
        ipv4_address: 172.16.238.4

networks:
  my-network:
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
